### ISSUE TITLE
No devices found in TTN (new version) v0.2.0

### ISSUE THREAD

**Issue by aechile** [angelnu/home_assistant_thethingsnetwork#15]
Hi everybody,
thank you very much for this integration! I succesfully conected HA to my TTN aplication with server hostname, APP-ID, APP Access Key with full rights and also activate the persistant storage function in the TTN aplication. Now my problem is that the integration doesn´t show up my devices. I have 3 Dragino test devices registered in the TTN APP which are recieving data from the sensors.

I don´t get any error o debug messages. Anybody have an advise how to find the problem?
Is there any know problem with this TTN server "nam1.cloud.thethings.network"

In the configuration.yaml I added following code for debbuging the TTN integration.
`
logger:
  default: critical
  logs:
    custom_components.thethingsnetwork: debug
`

I appreciate any ideas and help.
Kind regards.
Timo

**Comment by vincegre** [comment]
What type of sensor is it ? Have you reloaded the integration since you added devices in TTN console ?

**Comment by aechile** [comment]
Hi Vincegre,
yes I have reloaded and restartet HA serveral times.

The three sensors already registered and comunicating with TTN are:
- Temp. Humidity LHT65N
- Dry contact sensor CPL01
- RS485 Lorawan IoT

Kind regards

**Comment by vincegre** [comment]
> * Temp. Humidity LHT65N

I don't know for the other ones but this one I have same here and it works perfectly with the integration ! Does the integration shows devices ? have you setup the permanent storage as indicated in integration manual ?
![2023-03-14 10 28 54 n6i71nveptxx72q10614vld17u87jnhh ui nabu casa a8c023dc0c68](https://user-images.githubusercontent.com/3164888/224956825-a714aa07-140f-423e-b795-6f3aa7222103.png)

**Comment by aechile** [comment]
Hi Vincegre,
like mentioned above. The integration shows no error and no devices
![image](https://user-images.githubusercontent.com/74826979/225061859-a10a85f7-cc21-4f1d-8131-1e7d8a3d57de.png)

I still haven´t found the cause and solution. I already tried different API Keys but without result.
I am not sure how to debug the detail of the problem. 

Kind regards

**Comment by vincegre** [comment]
> I still haven´t found the cause and solution. I already tried different API Keys but without result.

Looks like a misconfiguration somewehere. You have well created the API key in the group in TTN console where are your sensors ?
Your sensors are well added in TTN console and you see messages received from these devices in TTN console ?

**Comment by paulbalinnel** [comment]
Hallo, I am following this because I have the same issue. The sensors are in live in TTN, the have data. I have tried changing API, I also have no sensors in HASS 
<img width="492" alt="Screenshot 2023-03-15 at 12 22 09" src="https://user-images.githubusercontent.com/89601096/225280699-a7bdb679-3476-4f7f-9e98-ba8832fa6006.png">

**Comment by aechile** [comment]
> > I still haven´t found the cause and solution. I already tried different API Keys but without result.
> 
> Looks like a misconfiguration somewehere. You have well created the API key in the group in TTN console where are your sensors ? Your sensors are well added in TTN console and you see messages received from these devices in TTN console ?

Hi, 
I tried different API keys with different rights for the Application-ID (group). Also I can confirm that the devices are recieving messages in the TTN console.
![image](https://user-images.githubusercontent.com/74826979/225313942-060e2c4c-f326-48ca-b56a-7edf81d1e735.png)

Please can you tell me if the configuration settings in the TTN HA integration are correct the devices show up immedeatly or it needs some time to show up ?

Kind regards

**Comment by vincegre** [comment]
> Please can you tell me if the configuration settings in the TTN HASS integration are correct the devices show up immedeatly or it needs some time to show up ?

It shows quite immediately but the integration is only able to report basic sensors and if they have a payload in a specific format :( I'm quite sure it's reason why you don't see yours showing up in integration. Here I have some Dragino temp/hum sensors that are working fine but I have some 4 buttons remote and these ones are not handled properly by the integration and unhappy that new integration is not really supported by its developer too (not a critic, just a reality) so I don't expect some new type of devices to be supported soon in the integration :/

**Comment by aechile** [comment]
> > Please can you tell me if the configuration settings in the TTN HASS integration are correct the devices show up immedeatly or it needs some time to show up ?
> 
> It shows quite immediately but the integration is only able to report basic sensors and if they have a payload in a specific format :( I'm quite sure it's reason why you don't see yours showing up in integration. Here I have some Dragino temp/hum sensors that are working fine but I have some 4 buttons remote and these ones are not handled properly by the integration and unhappy that new integration is not really supported by its developer too (not a critic, just a reality) so I don't expect some new type of devices to be supported soon in the integration :/

Hi Vincegre,
the payload is quite simple  and looks like that. I hope this is not the problem. I still haven´t found a solution.
`      "decoded_payload": {
        "Bat": 3.3,
        "Hardware_flag": 0,
        "Interrupt_flag": 0,
        "Sensor_flag": 1,
        "TempC_DS18B20": "0.00",
        "conduct_SOIL": 105,
        "temp_SOIL": "21.09",
        "water_SOIL": "20.13"
      },`

**Comment by aechile** [comment]
Hi, any help to solve this? The sensors (7x Dragino) are all in live in TTN, the have data. I have tried changing API but don´t see 
 any sensors in HASS.
Kind regards

**Comment by vincegre** [comment]
> Hi, any help to solve this? The sensors (7x Dragino) are all in live in TTN, the have data. I have tried changing API but don´t see

Well as tags are not really standard I think your only option is the traditional mqtt way that works great with TTN since always ;)

**Comment by aechile** [comment]
Ok, anyone has a working example for the MQTT sensor from TTN? I have already the following but the sensor has no value. Anybody see some errors? 

```
# Bridge to The Things Network in file "/config/mosquitto.conf"
connection bridge
address nam1.cloud.thethings.network:8883
remote_username "xxx"
remote_password "xxx"
bridge_insecure false
topic # both 0
```

And in the configuration.yaml the following MQTT test sensor:

```
#create new mqqt sensor with template from TTN
mqtt:
  sensor:
  - name: Dragino_RS485
    device_class: "voltage"
    unit_of_measurement: "V"
    state_topic: "v3/iot-monitor@ttn/devices/eui-a8404177a18697a2/up"
    value_template: "{{ value_json.uplink_message.decoded_payload.BatV }}"
```

Thanks and Kind regards

**Comment by vincegre** [comment]
> ```
> # Bridge to The Things Network in file "/config/mosquitto.conf"
> connection bridge
> address nam1.cloud.thethings.network:8883
> remote_username "xxx"
> remote_password "xxx"
> bridge_insecure false
> topic # both 0
> ```

I use that code for the bridge since always:

```
connection boutons-inputs
address eu1.cloud.thethings.network
bridge_protocol_version mqttv311
remote_username xxxx@ttn
start_type automatic
notifications false
try_private false
remote_password NNSXS.xxxxxxx
bridge_insecure true
topic # in 0
cleansession true
```
> And in the configuration.yaml the following MQTT test sensor:
> ```
> #create new mqqt sensor with template from TTN
> mqtt:
>   sensor:
>   - name: Dragino_RS485
>     device_class: "voltage"
>     unit_of_measurement: "V"
>     state_topic: "v3/iot-monitor@ttn/devices/eui-a8404177a18697a2/up"
>     value_template: "{{ value_json.uplink_message.decoded_payload.BatV }}"
> ```

It can't work that part as according at payload you shared previously it returns Bat field and not BatV ;-)

**Comment by holtkamp** [comment]
> Hallo, I am following this because I have the same issue. The sensors are in live in TTN, the have data. I have tried changing API, I also have no sensors in HASS <img alt="Screenshot 2023-03-15 at 12 22 09" width="492" src="https://user-images.githubusercontent.com/89601096/225280699-a7bdb679-3476-4f7f-9e98-ba8832fa6006.png">

I had the same issue, the cause was a configuration mistake. 

The configuration panel in Home Assistant does not perform any validation. 

Make sure: 
1. the hostname does not begin with `https://`
2. the API key should be copy pasted when generating the API key in the TTN application console (and is NOT the same as the API Key ID

Enabling the debug log for the integration and checking it out (settings => system => logs) made me discover my mistakes

First mistake: I copy pasted the hostname including the protocol `https://`, this resulted in errors like: 

```
Error while accessing: https://https://my-project-name.eu1.cloud.thethings.industries
```

Second mistake: when removing the integration from Home Assistant and try adding it again, I copy pasted the API Key ID (instead of the API key during creation), which resulted in errors like: 

```
TTN entry without result: {'error': {'code': 3, 'message': 'error:pkg/auth:token (invalid token)'
```

Maybe some validation can be added to the configuration panel to prevent these mistakes?

**Comment by vincegre** [comment]
> Maybe some validation can be added to the configuration panel to prevent these mistakes?

Don't expect it to happen, the author of the integration is away since ages on that repository (no answers at issues opened by users, and no update of integration since initial release a year ago or something like that :-1:

**Comment by angelnu** [comment]
This custom integration is deprecated as it has been integrated into the core HA since 2024.6.

Please migrate.

**Comment by holtkamp** [comment]
Thanks for the hard work on https://github.com/home-assistant/core/pull/113375 @angelnu !

Some links for quick reference:
- https://www.home-assistant.io/blog/2024/06/05/release-20246/#noteworthy-improvements-to-existing-integrations
- https://www.home-assistant.io/integrations/thethingsnetwork
