### ISSUE TITLE
Warning "using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state()"

### ISSUE THREAD

**Issue by kalon33** [angelnu/home_assistant_thethingsnetwork#17]
Hi,

I got the following message in home assistant log when my ttn v3 device is sending messages (for each of the entities retrieved) :

`2023-05-27 15:20:42.271 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.trackit_ennio_batt (<class 'custom_components.thethingsnetwork.TTN_client.TtnDataSensor'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.`

Could you have a look for a fix? Thanks for your help.

**Comment by dickeos** [comment]
Plus 1 on the above problem. It seems only to happen with certain applications.

**Comment by holtkamp** [comment]
@kalon33 and @dickeos, does this warning message breaks the functioning of the integration, or is it just a "warning" without side-effects?

**Comment by angelnu** [comment]
fixed at https://github.com/angelnu/home_assistant_thethingsnetwork/commit/ccf6fb6e1086817d5c00ca86d1bc06839e056c7a
