### ISSUE TITLE
how to configure?

### ISSUE THREAD

**Issue by radu022003** [angelnu/home_assistant_thethingsnetwork#18]
Hello,
i have just installed the version 0.2.0 on my HomeAssistant and I got this card for configuration:
![image](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/7964240/cd24d137-1f8e-482e-9b38-474880bb52e2)

I have no clue what should be filled in the two empty slots.

**Comment by angelnu** [comment]
no... it should show the following:

![imagen](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/4406403/52228657-c3bb-4643-bb08-d4ace2af8cbb)

No idea why for you is empty - perhaps a problem with styles? Can you check with a light theme?

**Comment by radu022003** [comment]
I can try later with a light theme, but at the moment I have tried with a dark theme from the Android app and looks good.
![image](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/7964240/fd869e8f-3cc4-4cb9-8430-5cc89d2295a9)

**Comment by pgm1968** [comment]
If you have entered this data is there a way to change it.

**Comment by angelnu** [comment]
This custom integration is deprecated as it has been integrated into the core HA since 2024.6. 

Please migrate.
