### ISSUE TITLE
deprecated device_state_attributes

### ISSUE THREAD

**Issue by ei-ke** [angelnu/home_assistant_thethingsnetwork#2]
From the log:
```
2021-12-20 11:22:15 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.attnode_001_v (<class 'custom_components.thethingsnetwork.TTN_client.TtnDataSensor'>) implements device_state_attributes. Please report it to the custom component author.
```
I've changed
`def device_state_attributes(self) -> Optional[Dict[str, Any]]:`
to
`def extra_state_attributes(self) -> Optional[Dict[str, Any]]:`
on [L469](https://github.com/angelnu/home_assistant_thethingsnetwork/blob/08a40d1fa8a73575ab7b5b598837d4688f30af31/custom_components/thethingsnetwork/TTN_client.py#L469)

Not sure if [that's the solution](https://github.com/jsBlackBelt/localtuya/commit/bfba2d7f722b2bacc221f9da3d4beba4b7e1417a), but the warning is gone.

**Comment by angelnu** [comment]
Likely device_state_attributes has been deprecated in favor of extra_state_attributes.

Will take your change - thanks!

**Comment by angelnu** [comment]
Fixed with https://github.com/angelnu/home_assistant_thethingsnetwork/commit/6b034c1da40caa2ecc8dfb8089da2c5a1b4a57a8
