### ISSUE TITLE
No devices or entities

### ISSUE THREAD

**Issue by HansPeterDurand** [angelnu/home_assistant_thethingsnetwork#24]
Good afternoon,
I managed to installHome Assistant wir Zigbee and various other Integrations. Actually i am working on the TTN intergation. Gateway and sensor work (up to now finde). I also managed to install the new "The Tings Network" Integration. So far so good(or not). On the things network console i create an API Key, that will be used for the registartion. In HA I used  as requestet the created API Key (copied/past) and the application ID "ms24-letterbox". As a result I got the message from HA: No devices or entites? For this is strange. Have I missed someting?

besten regards for any hint.

Hans Peter

--------------------------------------------------excerpt from the log file-----------------------------------------------
![Screenshot 2024-03-16 154015](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/5a491e6a-be67-49cd-b638-0bb9228b9317)
![Screenshot 2024-03-16 154015](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/f5093a45-3d9e-4668-a655-cfb87c5831a3)

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.thethingsnetwork
Quelle: custom_components/thethingsnetwork/TTN_client.py:204
Integration: The Things Network (Dokumentation, Probleme)
Erstmals aufgetreten: 14:41:41 (12 Vorkommnisse)
Zuletzt protokolliert: 15:25:55

TTN entry without result: {'error': {'code': 3, 'message': 'error:pkg/auth:token (invalid token)', 'details': [{'@type': 'type.googleapis.com/ttn.lorawan.v3.ErrorDetails', 'namespace': 'pkg/auth', 'name': 'token', 'message_format': 'invalid token', 'correlation_id': 'ed70b8418fb24509a2f0302fddf1bdd0', 'code': 3}]}}
TTN entry without result: {'error': {'code': 3, 'message': 'error:pkg/auth:token (invalid token)', 'details': [{'@type': 'type.googleapis.com/ttn.lorawan.v3.ErrorDetails', 'namespace': 'pkg/auth', 'name': 'token', 'message_format': 'invalid token', 'correlation_id': 'ef5b4db91e1445f184dc0f21a36843a6', 'code': 3}]}}
TTN entry without result: {'error': {'code': 3, 'message': 'error:pkg/auth:token (invalid token)', 'details': [{'@type': 'type.googleapis.com/ttn.lorawan.v3.ErrorDetails', 'namespace': 'pkg/auth', 'name': 'token', 'message_format': 'invalid token', 'correlation_id': 'dc5bf9a17b6c42c9808e1a2a560137b8', 'code': 3}]}}
TTN entry without result: {'error': {'code': 3, 'message': 'error:pkg/auth:token (invalid token)', 'details': [{'@type': 'type.googleapis.com/ttn.lorawan.v3.ErrorDetails', 'namespace': 'pkg/auth', 'name': 'token', 'message_format': 'invalid token', 'correlation_id': 'b563f95d30fc47daa8da2182c820780d', 'code': 3}]}}
TTN entry without result: {'error': {'code': 3, 'message': 'error:pkg/errors:validation (invalid `application_ids`: embedded message failed validation)', 'details': [{'@type': 'type.googleapis.com/ttn.lorawan.v3.ErrorDetails', 'namespace': 'pkg/errors', 'name': 'validation', 'message_format': 'invalid `{field}`: {reason}', 'attributes': {'field': 'application_ids', 'name': 'GetStoredApplicationUpRequestValidationError', 'reason': 'embedded message failed validation'}, 'correlation_id': '90bbe75ab26d4e86b0d350335ffa5b27', 'cause': {'namespace': 'pkg/errors', 'name': 'validation', 'message_format': 'invalid `{field}`: {reason}', 'attributes': {'field': 'application_id', 'name': 'ApplicationIdentifiersValidationError', 'reason': 'value does not match regex pattern "^[a-z0-9](?:[-]?[a-z0-9]){2,}$"'}, 'correlation_id': 'db1d96c01415447794985a710b3c7691', 'code': 3}, 'code': 3}]}}

**Comment by angelnu** [comment]
Hi @HansPeterDurand . Did you enable the storage API in TheThingsNetwork? This might be the problem.

Btw: I am working towards submitting this code into the Home Assustant core code to replace the broken v2 there. I am thinking about checking if the storage api is set.

**Comment by HansPeterDurand** [comment]
Good morning Angel,
Thank you for your hint. I checked the configuration. Storage has been configured (see attachment).
![Screenshot 2024-03-17 091532](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/05a4ae42-37aa-4438-9304-49d7b853b51c)

In addition I created a new API Key an registered the application "ms24-letterbox". 
![Screenshot 2024-03-17 092246](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/85e54a51-0713-41d1-96f1-11a7018202a1)
As a result i got a success message:
![Screenshot 2024-03-17 092352](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/ac5b89f5-d295-4e6b-8aeb-a461432f6be4)
So far so good. On Home Assistant I still get this message (no devices or entities).
![Screenshot 2024-03-17 093244](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/bebb7b8a-23bc-4038-84f5-d0d0a1a40f51)
Interesting aspect: Having a look into the "Protokoll" I see no entry (last timestamp: 09:09:13 from another integration)!
![Screenshot 2024-03-17 094007](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/67cb7cfc-9793-4ed8-920f-aae748693490)

Seems that, I came a step further?

regards

Hans Peter

**Comment by angelnu** [comment]
@HansPeterDurand if you do not see errors in the integration logs then there are 2 things to check next:
- did the ttn device send an unlink in the last 24 hours (the free ttn storage retention). You might want to use the the storage api example to check.
- does the unlink message contain a `decoded_payload` entry? Each value in it will get added as home assistant entity

**Comment by HansPeterDurand** [comment]
Hello Angel,
I had a look at the logs and couldn't find an unlink message. Up to know I can say that the Device as well as the gateway work as  they should do (see below)

![Screenshot 2024-03-17 123023](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/aa02ace0-038b-4faf-802b-2135ef07a042)
![Screenshot 2024-03-17 123108](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/48702f3f-7e9d-4dfa-bfcb-410ba2ecdc49)

I'll check the configuration with a colleague that has an almost similar configuration.

Regards
Hans Peter

**Comment by angelnu** [comment]
uplinks are what is needed (typo in my reply) and you seem to have plenty. But do you have payload formarters:
<img width="1712" alt="image" src="https://github.com/angelnu/home_assistant_thethingsnetwork/assets/4406403/2802efa6-310f-48b2-8c54-1dee70b10ffc">
This is how the `decode_payload `looks in one of my uploads:
<img width="240" alt="image" src="https://github.com/angelnu/home_assistant_thethingsnetwork/assets/4406403/eb8e0417-0231-4564-a5cd-84337a3be62a">

**Comment by HansPeterDurand** [comment]
Hello Angel here i am again :-)
Up to now i havent defined any payload formater. So i choose the "Custom Javascript Formater". I copie the payload from the last message (see attachment)
![Screenshot 2024-03-17 194951](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/e8d0bd01-6dbf-480d-8068-106708e78915)

You see the result below.  In the message I see that the gateway id ist "test". Strange...

{
  "f_port": 1,
  "frm_payload": "DkZ//wAAAP////8=",
  "decoded_payload": {
    "bytes": [
      14,
      70,
      127,
      255,
      0,
      0,
      0,
      255,
      255,
      255,
      255
    ]
  },
  "rx_metadata": [
    {
      "gateway_ids": {
        "gateway_id": "test"
      },
      "rssi": 42,
      "channel_rssi": 42,
      "snr": 4.2
    }
  ],
  "settings": {
    "data_rate": {
      "lora": {
        "bandwidth": 125000,
        "spreading_factor": 7
      }
    },
    "frequency": "868000000"
  }
}

**Comment by angelnu** [comment]
The gateway `test` comes from testing the payload formater
<img width="631" alt="image" src="https://github.com/angelnu/home_assistant_thethingsnetwork/assets/4406403/dd1b2599-d8b7-4a96-addc-3de3feaa2775">

But at least you should get an entity in home assistant called bytes with the values being the array - not very useful yet but at least it would show that the integration is working.

For getting more useful values you will need a decoder matching your device. You have more information in this page: https://www.thethingsindustries.com/docs/integrations/payload-formatters/ I personally build my own devices so I use the Cayenne format but each TTN vendor can decide its own format.

**Comment by HansPeterDurand** [comment]
Hi Angel,
In the meantime, I have discussed my problem with my colleague. We will compare and document our installation in the coming days. I have looked at the topic of decoders (the sensor is from Dragino, type SN50v3-LB/LS). The supplier has linked a decoder file in his description (https://github.com/dragino/dragino-end-node-decoder/tree/main/SN50_v3-LB). I downloaded this file and used it as "Custom Javascript Formatter". 
When configuring the sensor, I selected "Use Device Repository Formatters". The result is that the live data is now output in formatted form. That looks better now. It now looks better on the Home Assistant page. Now one device and 10 entities are visible! As far as I can tell, thanks to your help, I have made a big step forward. Unfortunately I have to stop now, I still have a few other things to do. I will document the final situation.

Thanks again!

Translated with DeepL.com (free version)
![Screenshot 2024-03-18 192959](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/d5a6c7f0-02fd-4a15-a792-7249b3303c54)
![Screenshot 2024-03-18 194254](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/24ea694b-5526-41fd-9132-ee6960aa3fbe)
![Screenshot 2024-03-18 194416](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/155103102/a267118b-1e06-4605-bb7f-ec5f41479cf7)

**Comment by angelnu** [comment]
Jep, thislooks right. So let us close this for now.

Please notice that I added some words about the decoders to the documentation PRr at https://github.com/home-assistant/home-assistant.io/pull/31930 but as this part was too implicit before
