### ISSUE TITLE
Log Warnings Dragino LDS02 Door Sensor

### ISSUE THREAD

**Issue by stadelES** [angelnu/home_assistant_thethingsnetwork#25]
I found some warnings in the log:

Entity sensor.garage_tor_sensor_bat_v (<class 'custom_components.thethingsnetwork.TTN_client.TtnDataSensor'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please create a bug report at https://github.com/angelnu/home_assistant_thethingsnetwork/issues
Entity sensor.garage_tor_sensor_door_open_status (<class 'custom_components.thethingsnetwork.TTN_client.TtnDataSensor'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please create a bug report at https://github.com/angelnu/home_assistant_thethingsnetwork/issues
Entity sensor.garage_tor_sensor_door_open_times (<class 'custom_components.thethingsnetwork.TTN_client.TtnDataSensor'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please create a bug report at https://github.com/angelnu/home_assistant_thethingsnetwork/issues
Entity sensor.garage_tor_sensor_last_door_open_duration (<class 'custom_components.thethingsnetwork.TTN_client.TtnDataSensor'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please create a bug report at https://github.com/angelnu/home_assistant_thethingsnetwork/issues
Entity sensor.garage_tor_sensor_mod (<class 'custom_components.thethingsnetwork.TTN_client.TtnDataSensor'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please create a bug report at https://github.com/angelnu/home_assistant_thethingsnetwork/issues

Device is an Dragino LDS02 Door Sensor

**Comment by angelnu** [comment]
Thanks for reporting it @stadelES .

We are in the process of upgrading the ttn support directly in home assistant so this custom integration will not be needed. The new code at https://github.com/home-assistant/core/pull/113375 uses a  coordinator so this warning is fixed.

**Comment by radskin** [comment]
I have this sensor, but I don't know how to connect the sensor to home assistant to TTN.
I have installed the "Home Assistant integration for The Things Network" but my home Assistant doesn't recognize my devices from TTN. Where can I find some tutorial about that ? 

![image](https://github.com/angelnu/home_assistant_thethingsnetwork/assets/37718653/86c3d71d-03ee-442e-ab66-3d12ff8faa8c)

**Comment by angelnu** [comment]
This custom integration is deprecated as it has been integrated into the core HA since 2024.6.

Please migrate.
