### ISSUE TITLE
Number of Devices issue

### ISSUE THREAD

**Issue by brynnneilson** [angelnu/home_assistant_thethingsnetwork#4]
Sorry bro, another bug. I just added a friend's TTN Application that has 11 devices and when I added it, it said 11 devices but once added, it only shows 1 device. Any idea why it would do that? 

BTW. Really appreciate that you created this custom component. It's really important for HA and the only way that I could integrate my sensors. If you have a way to donate, let me know.

**Comment by angelnu** [comment]
Could you share the log for the component after doing a restart of the adapter? It should share more details on what is being detected.

In my HA I have 50+ TTN devices but they all belong to the same application.

And no need to donate - I needed this for myself so if it can help others nice side effect!

**Comment by brynnneilson** [comment]
Sorry. Working now after I did a reboot.
